import {
    createMdxComponents,
    type MdxComponentMap,
    AccordionGroupMdx,
    AccordionMdx,
    CardGroupMdx,
    ChangesMdx,
    CodeBlock,
    FileMdx,
    FilesMdx,
    FolderMdx,
    KbdMdx,
    NoteMdx,
    ReleaseMdx,
    StepperItemMdx,
    StepperMdx,
    TableBodyMdx,
    TableCellMdx,
    TableFooterMdx,
    TableHeadMdx,
    TableHeaderMdx,
    TableMdx,
    TableRowMdx,
    TabsContentMdx,
    TabsListMdx,
    TabsMdx,
    TabsTriggerMdx,
    TooltipMdx,
    YoutubeMdx,
} from "@docubook/mdx-content";
import { ImageMdx, LinkMdx, ButtonMdx, CardMdx } from "@docubook/mdx-content/next";
import { customMdxComponents } from "@/lib/mdx";

const builtInOverrides: MdxComponentMap = {
    Tabs: TabsMdx,
    TabsContent: TabsContentMdx,
    TabsList: TabsListMdx,
    TabsTrigger: TabsTriggerMdx,
    table: TableMdx,
    thead: TableHeaderMdx,
    tbody: TableBodyMdx,
    tfoot: TableFooterMdx,
    tr: TableRowMdx,
    th: TableHeadMdx,
    td: TableCellMdx,
    pre: CodeBlock,
    Card: CardMdx,
    Button: ButtonMdx,
    Note: NoteMdx,
    Stepper: StepperMdx,
    StepperItem: StepperItemMdx,
    Accordion: AccordionMdx,
    AccordionGroup: AccordionGroupMdx,
    CardGroup: CardGroupMdx,
    Kbd: KbdMdx,
    Release: ReleaseMdx,
    Changes: ChangesMdx,
    File: FileMdx,
    Files: FilesMdx,
    Folder: FolderMdx,
    Youtube: YoutubeMdx,
    Tooltip: TooltipMdx,
    img: ImageMdx,
    a: LinkMdx,
    Link: LinkMdx,
};

export const mdxComponents = createMdxComponents({
    ...builtInOverrides,
    ...customMdxComponents,
});
