import type { ComponentType } from "react";
import {
    AccordionMdx,
    AccordionsMdx,
    AccordionGroupMdx,
    ButtonMdx,
    CardsMdx,
    CardGroupMdx,
    CardMdx,
    CodeBlock,
    FileMdx,
    FilesMdx,
    FolderMdx,
    ImageMdx,
    KbdMdx,
    LinkMdx,
    NoteMdx,
    ReleaseMdx,
    ChangesMdx,
    StepMdx,
    StepsMdx,
    StepperItemMdx,
    StepperMdx,
    TooltipMdx,
    YoutubeMdx,
} from "../components";
import {
    TableBodyMdx,
    TableCellMdx,
    TableFooterMdx,
    TableHeadMdx,
    TableHeaderMdx,
    TableMdx,
    TableRowMdx,
} from "../components/TableMdx";
import { TabMdx, TabsContentMdx, TabsListMdx, TabsMdx, TabsTriggerMdx } from "../components/TabsMdx";

export type MdxComponentMap = Record<string, ComponentType<any>>;

export function createMdxComponents(customComponents: MdxComponentMap = {}): MdxComponentMap {
    return {
        Tabs: TabsMdx,
        Tab: TabMdx,

        // Legacy tabs API aliases for migration compatibility
        TabsList: TabsListMdx,
        TabsTrigger: TabsTriggerMdx,
        TabsContent: TabsContentMdx,
        table: TableMdx,
        thead: TableHeaderMdx,
        tbody: TableBodyMdx,
        tfoot: TableFooterMdx,
        tr: TableRowMdx,
        th: TableHeadMdx,
        td: TableCellMdx,
        pre: CodeBlock,
        a: LinkMdx,
        Link: LinkMdx,
        Card: CardMdx,
        Button: ButtonMdx,
        Note: NoteMdx,
        Steps: StepsMdx,
        Step: StepMdx,
        Stepper: StepperMdx,
        StepperItem: StepperItemMdx,
        Accordion: AccordionMdx,
        Accordions: AccordionsMdx,
        AccordionGroup: AccordionGroupMdx,
        Cards: CardsMdx,
        CardGroup: CardGroupMdx,
        Kbd: KbdMdx,
        Release: ReleaseMdx,
        Changes: ChangesMdx,
        File: FileMdx,
        Files: FilesMdx,
        Folder: FolderMdx,
        Image: ImageMdx,
        img: ImageMdx,
        Youtube: YoutubeMdx,
        Tooltip: TooltipMdx,
        ...customComponents,
    };
}
